/// Species that have a Mega Evolution in the games.
///
/// The Pokédex index contains a `-mega` entry for far more species than
/// actually have one: `venusaur-mega` and `blastoise-mega` are leftovers from
/// a cut feature and are shipped with artwork, cries and moves like any other
/// form. Nothing in the payload distinguishes them, so the set is curated here.
///
/// Entries with a base name outside this set are not offered as forms and do
/// not make the base card advertise a Mega.
const Set<String> kMegaEvolutionSpecies = {
  'absol',
  'aerodactyl',
  'aggron',
  'alakazam',
  'altaria',
  'ampharos',
  'banette',
  'beedrill',
  'blacephalon',
  'blaziken',
  'camerupt',
  'charizard',
  'dialga',
  'diancie',
  'dragalge',
  'gallade',
  'gengar',
  'genesect',
  'gardevoir',
  'glalie',
  'golurk',
  'greninja',
  'grimmsnarl',
  'groudon',
  'gyarados',
  'hawlucha',
  'heracross',
  'hoopa',
  'houndoom',
  'keldeo',
  'kangaskhan',
  'kyogre',
  'kyurem',
  'latias',
  'latios',
  'lickitung',
  'lopunny',
  'lucario',
  'magearna',
  'manectric',
  'marowak',
  'mawile',
  'medicham',
  'meloetta',
  'meowstic',
  'metagross',
  'mewtwo',
  'naganadel',
  'pidgeot',
  'pheromosa',
  'pinsir',
  'raichu',
  'rayquaza',
  'sableye',
  'salamence',
  'sceptile',
  'scizor',
  'sharpedo',
  'slowbro',
  'stakataka',
  'steelix',
  'swampert',
  'tyranitar',
  'urshifu',
  'vikavolt',
  'xurkitree',
  'zacian',
  'zamazenta',
};
